#include <iostream>
using namespace std;

int main(){
int n = 4;

char ch = 'A';

for(int i=0; i<n; i++){
    for (int j=i; j>=0; j--){
        cout << char('A'+j) << " ";
        ch++;
    }
    cout << endl;
}

    return 0;
}



// Output:
// A
// B A
// C B A
// D C B A      

// Output Explanation:
// In the first row, we print 'A' (which is 'A' + 0).
// In the second row, we print 'B' (which is 'A' + 1) followed by 'A' (which is 'A' + 0).
// In the third row, we print 'C' (which is 'A' + 2), 'B' (which is 'A' + 1), and 'A' (which is 'A' + 0).
// In the fourth row, we print 'D' (which is 'A' + 3), 'C' (which is 'A' + 2), 'B' (which is 'A' + 1), and 'A' (which is 'A' + 0).      
// The pattern is generated by using the ASCII values of characters. The outer loop iterates through each row, and the inner loop prints characters in reverse order starting from 'A' + i down to 'A'.
